// File: lib/firebase_options.dart
// Auto-generated by FlutterFire CLI

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqw-T34BfiXtAZsGfgztqnaCb8o1IX1E',
    authDomain: 'safesphere-15a22.firebaseapp.com',
    projectId: 'safesphere-15a22',
    storageBucket: 'safesphere-15a22.firebasestorage.app',
    messagingSenderId: '969413027413',
    appId: '1:969413027413:web:your-web-app-id',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADqw-T34BfiXtAZsGfgztqnaCb8o1IX1E',
    authDomain: 'safesphere-15a22.firebaseapp.com',
    projectId: 'safesphere-15a22',
    storageBucket: 'safesphere-15a22.firebasestorage.app',
    messagingSenderId: '969413027413',
    appId: '1:969413027413:android:5e085c4ac7d83174f516dc',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqw-T34BfiXtAZsGfgztqnaCb8o1IX1E',
    authDomain: 'safesphere-15a22.firebaseapp.com',
    projectId: 'safesphere-15a22',
    storageBucket: 'safesphere-15a22.firebasestorage.app',
    messagingSenderId: '969413027413',
    appId: '1:969413027413:ios:your-ios-app-id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADqw-T34BfiXtAZsGfgztqnaCb8o1IX1E',
    authDomain: 'safesphere-15a22.firebaseapp.com',
    projectId: 'safesphere-15a22',
    storageBucket: 'safesphere-15a22.firebasestorage.app',
    messagingSenderId: '969413027413',
    appId: '1:969413027413:ios:your-macos-app-id',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADqw-T34BfiXtAZsGfgztqnaCb8o1IX1E',
    authDomain: 'safesphere-15a22.firebaseapp.com',
    projectId: 'safesphere-15a22',
    storageBucket: 'safesphere-15a22.firebasestorage.app',
    messagingSenderId: '969413027413',
    appId: '1:969413027413:web:your-windows-app-id',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyADqw-T34BfiXtAZsGfgztqnaCb8o1IX1E',
    authDomain: 'safesphere-15a22.firebaseapp.com',
    projectId: 'safesphere-15a22',
    storageBucket: 'safesphere-15a22.firebasestorage.app',
    messagingSenderId: '969413027413',
    appId: '1:969413027413:web:your-linux-app-id',
  );
}